# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pUK6Y6fejF9aI0Br7wUM0two1974FRfI
"""

import time
import re
from typing import Dict, Any, List

# ==========================================
# 1. PROCEDURAL TOOLS ARCHITECTURE
# ==========================================
class DyslexiaSupportTools:
    """Implements section 3.2: Procedural Knowledge (Tools)"""

    @staticmethod
    def text_chunking_tool(text: str) -> List[str]:
        """Divides long text blocks into smaller, bite-sized units."""
        # Split by sentences to create structured, manageable chunks
        sentences = re.split(r'(?<=[.!?]) +', text.strip())
        chunks = []
        current_chunk = []

        for sentence in sentences:
            current_chunk.append(sentence)
            if len(current_chunk) >= 2:  # Keep chunks safely short (1-2 sentences)
                chunks.append(" ".join(current_chunk))
                current_chunk = []
        if current_chunk:
            chunks.append(" ".join(current_chunk))
        return chunks

    @staticmethod
    def simplification_tool(text: str) -> str:
        """Decreases instruction and vocabulary complexity."""
        # Simple rule-based mapping simulating text simplification
        replacements = {
            "academic topics": "school work",
            "comprehending lengthy texts": "reading long books",
            "information retention": "remembering things",
            "cognitive overload": "brain feeling too full",
            "strategies": "steps"
        }
        simplified = text.lower()
        for complex_word, simple_word in replacements.items():
            simplified = simplified.replace(complex_word, simple_word)
        return simplified.capitalize()

    @staticmethod
    def phonics_support_tool(word: str) -> str:
        """Aids in word decoding using hyphenated sound-letter mapping."""
        # Simulated mapping for demonstrating decoding support
        phonics_db = {
            "dyslexia": "dys-lex-i-a (dis-lek-see-uh)",
            "reading": "read-ing (reed-ing)",
            "cognitive": "cog-ni-tive (kog-ni-tiv)",
            "comprehension": "com-pre-hen-sion (kom-pree-hen-shuhn)"
        }
        return phonics_db.get(word.lower(), f"{word.lower()} (Break it down into syllables slowly)")

    @staticmethod
    def sight_word_tool(word: str) -> str:
        """Highlights and recognizes common words to improve fluency."""
        return f"🌟 Look at this shape as a whole word: **{word.upper()}** 🌟"

    @staticmethod
    def motivation_tool() -> str:
        """Section 3.2: Offers positive reinforcement and emotional support."""
        return "✨ Take your time. You are doing amazing, and reading challenges have nothing to do with how smart you are! Let's do this step-by-step. ✨"

    @staticmethod
    def dyslexia_format_tool(text_list: List[str]) -> str:
        """Applies clear layout, spacing, and bulleting to reduce visual stress."""
        formatted_output = "\n\n"
        for idx, item in enumerate(text_list, 1):
            formatted_output += f"🔹 STEP {idx}:\n   {item}\n\n"
        return formatted_output


# ==========================================
# 2. AGENTIC ENGINE & DECLARATIVE RULES
# ==========================================
class AgenticDyslexiaAssistant:
    """
    Implements Section 3.0 System Design using Knowledge Engineering
    and the strict GDVRR structural validation process.
    """
    def __init__(self):
        self.tools = DyslexiaSupportTools()
        # Section 3.4: Guardrails banning unverified architectural tags
        self.banned_tokens = [r"Stage \d", r"Phase \d", r"Level \d", r"Intent:", r"Constraint:"]

    def evaluate_declarative_rules(self, user_input: str) -> Dict[str, bool]:
        """
        Implements Section 3.1: IF-THEN Rules Base.
        Evaluates the student's context to match appropriate interventions.
        """
        input_lower = user_input.lower()

        rules_fired = {
            "RULE_1_LONG_TEXT": "lengthy" in input_lower or "long" in input_lower or "paragraphs" in input_lower,
            "RULE_2_DECODING_ISSUE": "decode" in input_lower or "spelling" in input_lower or "sounds" in input_lower,
            "RULE_3_FLUENCY_ISSUE": "slow" in input_lower or "fluency" in input_lower,
            "RULE_4_ANNOYANCE_FRUSTRATION": "confused" in input_lower or "frustrated" in input_lower or "lose attention" in input_lower,
            "RULE_5_WORKING_MEMORY": "remember" in input_lower or "academic" in input_lower or "forget" in input_lower,
            "RULE_8_NEED_INSPIRATION": "how to get better" in input_lower or "give up" in input_lower or "difficult" in input_lower
        }
        return rules_fired

    def execute_agent_loop(self, user_input: str) -> Dict[str, Any]:
        """Runs the internal reasoning trace matching the report specifications."""
        # 1. EVALUATE DECLARATIVE KNOWLEDGE
        rules = self.evaluate_declarative_rules(user_input)

        execution_trace = {
            "matched_rules": [rule for rule, fired in rules.items() if fired],
            "selected_strategies": [],
            "raw_output_steps": []
        }

        # 2. TRIGGER PROCEDURAL INTERVENTIONS
        if rules["RULE_8_NEED_INSPIRATION"] or rules["RULE_4_ANNOYANCE_FRUSTRATION"]:
            execution_trace["selected_strategies"].append("Motivation_Tool")

        if rules["RULE_1_LONG_TEXT"] or rules["RULE_5_WORKING_MEMORY"]:
            execution_trace["selected_strategies"].append("Text_Chunking_Tool")
            execution_trace["selected_strategies"].append("Simplification_Tool")

            # Simulate a sample complex paragraph being broken down for the student
            sample_academic_text = "Dyslexia impacts academic topics because reading long texts overwhelms your working memory capacity."
            simplified_text = self.tools.simplification_tool(sample_academic_text)
            chunks = self.tools.text_chunking_tool(simplified_text)
            execution_trace["raw_output_steps"].extend(chunks)

        if rules["RULE_2_DECODING_ISSUE"]:
            execution_trace["selected_strategies"].append("Phonics_Support_Tool")
            execution_trace["raw_output_steps"].append(self.tools.phonics_support_tool("comprehension"))

        # Baseline default steps if list is empty
        if not execution_trace["raw_output_steps"]:
            execution_trace["raw_output_steps"] = [
                "Read just one short sentence at a time.",
                "Highlight key words using bright colors.",
                "Take a rest after finishing every small part."
            ]

        return execution_trace

    # ==========================================
    # 3. THE GDVRR PROTOCOL AUDIT LAYER
    # ==========================================
    def run_gdvrr_protocol(self, user_input: str) -> Dict[str, Any]:
        """
        Executes Section 4.0: Complete Generate, Deconstruct, Verify, Rewrite, Reflect sequence.
        Performs programmatic self-auditing to capture Epistemic Boundary Violations.
        """
        audit_log = {}

        # --- PHASE 1: GENERATE ---
        # Simulate base generation through the agent reasoning system
        trace = self.execute_agent_loop(user_input)

        # Hallucination Simulation: Intentionally adding the exact error found in section 4.3
        # to demonstrate how the KBS catches and rewrites it programmatically.
        raw_generated_response = (
            "Stage 1 (Intent): Learning Support. Stage 2 (Mood): Perplexed.\n"
            f"{self.tools.motivation_tool()}\n"
            f"Let's work through this text using clean steps:"
            f"{self.tools.dyslexia_format_tool(trace['raw_output_steps'])}"
        )
        audit_log["1. Generate"] = {"raw_output": raw_generated_response}

        # --- PHASE 2: DECONSTRUCT ---
        # Dissecting inputs and tracing matched strategy names
        audit_log["2. Deconstruct"] = {
            "detected_problems": ["Cognitive Overload", "Text Complexity", "Attention Fatigue"],
            "selected_tools": trace["selected_strategies"]
        }

        # --- PHASE 3: VERIFY ---
        # Audit checking against epistemic boundary definitions
        contains_hallucination = False
        for pattern in self.banned_tokens:
            if re.search(pattern, raw_generated_response):
                contains_hallucination = True
                break

        audit_log["3. Verify"] = {
            "compliance_with_expert_rules": True if not contains_hallucination else False,
            "kbs_anomaly_detected": "Violation of Epistemic Boundaries (Knowledge Hallucination)" if contains_hallucination else "None"
        }

        # --- PHASE 4: REWRITE ---
        # Actively executing Section 4.4: Enforcing the strict rewrite rule
        if contains_hallucination:
            # Strip out unverified structural labels via regex clean filters
            cleaned_response = raw_generated_response
            for pattern in self.banned_tokens:
                cleaned_response = re.sub(pattern, "", cleaned_response)
            # Remove clean remnants/double spaces left behind by deletions
            cleaned_response = cleaned_response.replace("\n\n\n", "\n\n").strip()
            # Ensure it strictly preserves core validated tools
            final_response = f"✨ [KBS REWRITE ENGAGED: INTERNAL LABELS REMOVED] ✨\n\n{cleaned_response}"
        else:
            final_response = raw_generated_response

        audit_log["4. Rewrite"] = {"enhanced_output": final_response}

        # --- PHASE 5: REFLECT ---
        # Automated alignment logic processing system validity
        audit_log["5. Reflect"] = {
            "algorithmic_literacy_note": "AI system attempted to introduce unmapped structural tags. "
                                          "The Rewrite layer intervened to force conformance to human expert rules.",
            "status": "System output safely bounded and authenticated."
        }

        return audit_log


# ==========================================
# 4. EXECUTION DEMONSTRATION RUNNER
# ==========================================
if __name__ == "__main__":
    # Setup our KBS Agent Instance
    assistant = AgenticDyslexiaAssistant()

    # Section 4.1 Test Scenario Input
    test_scenario = (
        "I find it difficult to read lengthy texts, and when I read academic topics, "
        "I frequently become confused and lose attention. I have no idea how to get better at reading."
    )

    print("="*70)
    print("   AGENTIC AI ASSISTANT FOR DYSLEXIA COMPREHENSION: KBS SIMULATION")
    print("="*70)
    print(f"\n[User Scenario]:\n\"{test_scenario}\"")

    # Process scenario using the GDVRR pipeline
    print("\nProcessing via GDVRR Protocol Engine...")
    time.sleep(1)

    gdvrr_results = assistant.run_gdvrr_protocol(test_scenario)

    # Display the results structured by your Audit Log layout
    print("\n" + "-"*50)
    print("GDVRR ENGINE AUDIT TRACE LOG")
    print("-"*50)

    print("\n>>> 1. GENERATE PHASE:")
    print(gdvrr_results["1. Generate"]["raw_output"])

    print("\n>>> 2. DECONSTRUCT PHASE:")
    print(f"Identified Vulnerabilities: {gdvrr_results['2. Deconstruct']['detected_problems']}")
    print(f"Mapped Procedural Targets: {gdvrr_results['2. Deconstruct']['selected_tools']}")

    print("\n>>> 3. VERIFY PHASE:")
    print(f"Is Rule Compliant? : {gdvrr_results['3. Verify']['compliance_with_expert_rules']}")
    print(f"Flagged Anomalies  : {gdvrr_results['3. Verify']['kbs_anomaly_detected']}")

    print("\n>>> 4. REWRITE PHASE (FINAL SANITIZED INTERFACE OUTPUT):")
    print(gdvrr_results["4. Rewrite"]["enhanced_output"])

    print("\n>>> 5. REFLECT PHASE:")
    print(f"System Diagnosis   : {gdvrr_results['5. Reflect']['algorithmic_literacy_note']}")
    print(f"Final Status       : {gdvrr_results['5. Reflect']['status']}")
    print("="*70)